repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.15.4"
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.37.0"
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
      - id: check-renovate
        args: ["--verbose"]
  - repo: local
    hooks:
      - id: zuban-type-check
        name: Zuban type check
        entry: uv run zuban check
        language: python
        types: [python]
